version: "3.9"
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/wwww
    volumes:
      - ./src:/var/www/
      - ./logs/php:/srv/var/log
    depends_on:
      - mariadb
    container_name: test
  mariadb:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      #MYSQL_USER: ${DB_USERNAME}
      #MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    container_name: mariadb
    volumes:
      - "./docker/mysql/:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mariadb
  nginx:
    image: nginx:1.8
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
