version: "3.8"

services:
  php:
    build: ./docker
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.8
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 100000000
    networks:
      - app-network
    depends_on:
      - mariadb

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
